name: Xray mipsle-softfloat

on:
  workflow_dispatch:
    inputs:
      version:
        description: Xray tag
        required: true
        default: v1.8.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install UPX
        run: sudo apt-get install -y upx

      - name: Clone Xray
        run: |
          git clone https://github.com/XTLS/Xray-core.git
          cd Xray-core
          git checkout "${{ github.event.inputs.version }}"

      - name: Build
        working-directory: Xray-core
        env:
          GOOS: linux
          GOARCH: mipsle
          GOMIPS: softfloat
          CGO_ENABLED: 0
          GOFLAGS: "-ldflags=-s -w"
        run: |
          go build -o xray ./main
          strip xray || true
          upx --best --lzma xray
          tar czf xray-mipsle-softfloat-${{ github.event.inputs.version }}.tar.gz xray

      - uses: actions/upload-artifact@v4
        with:
          name: xray-mipsle-softfloat-${{ github.event.inputs.version }}
          path: Xray-core/xray-mipsle-softfloat-${{ github.event.inputs.version }}.tar.gz
